CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`type` enum('cni','passeport','titre_sejour','autre') NOT NULL,
	`filename` varchar(256) NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`url` text NOT NULL,
	`mimeType` varchar(64),
	`size` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nom` varchar(128) NOT NULL,
	`nomJeuneFille` varchar(128),
	`prenoms` varchar(256) NOT NULL,
	`profession` varchar(128),
	`dateNaissance` varchar(32),
	`lieuNaissance` varchar(128),
	`adresse` text,
	`telephoneDomicile` varchar(32),
	`telephoneTravail` varchar(32),
	`telephonePortable` varchar(32),
	`email` varchar(320),
	`conjointNom` varchar(128),
	`conjointNomJeuneFille` varchar(128),
	`conjointPrenoms` varchar(256),
	`conjointProfession` varchar(128),
	`conjointDateNaissance` varchar(32),
	`conjointLieuNaissance` varchar(128),
	`conjointAdresse` text,
	`conjointTelephoneDomicile` varchar(32),
	`conjointTelephoneTravail` varchar(32),
	`conjointTelephonePortable` varchar(32),
	`conjointEmail` varchar(320),
	`communeMariage` varchar(128),
	`dateMariage` varchar(32),
	`contratMariage` boolean DEFAULT false,
	`regimeMatrimonial` varchar(128),
	`notaireContratNom` varchar(128),
	`notaireContratLieu` varchar(128),
	`notaireContratDate` varchar(32),
	`changementRegime` boolean DEFAULT false,
	`nouveauRegime` varchar(128),
	`notaireChangementNom` varchar(128),
	`notaireChangementLieu` varchar(128),
	`notaireChangementDate` varchar(32),
	`tribunalHomologation` varchar(128),
	`dateHomologation` varchar(32),
	`situationFamiliale` enum('celibataire','marie','divorce','instance_divorce','pacs','veuf') DEFAULT 'celibataire',
	`avocatNomAdresse` text,
	`tribunalDivorce` varchar(128),
	`dateDivorce` varchar(32),
	`exConjointNomPrenom` varchar(256),
	`datePacs` varchar(32),
	`partenairePacs` varchar(256),
	`nationalite` enum('francais','francais_etranger','etranger') DEFAULT 'francais',
	`statut` enum('nouveau','en_cours','traite','archive') NOT NULL DEFAULT 'nouveau',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
