CREATE TABLE `mandats_recherche` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`nom` varchar(128) NOT NULL,
	`prenoms` varchar(256) NOT NULL,
	`email` varchar(320) NOT NULL,
	`telephone` varchar(32) NOT NULL,
	`adresse` text,
	`dateNaissance` varchar(32),
	`lieuNaissance` varchar(128),
	`nationalite` varchar(64),
	`situationFamiliale` varchar(64),
	`typeBien` enum('appartement','maison','villa','terrain','local_commercial','autre') NOT NULL,
	`usage` enum('residence_principale','residence_secondaire','investissement_locatif') NOT NULL,
	`nbPiecesMin` int,
	`nbPiecesMax` int,
	`surfaceMin` int,
	`surfaceMax` int,
	`etage` varchar(64),
	`localisation` text NOT NULL,
	`etatBien` enum('neuf','ancien','les_deux') DEFAULT 'les_deux',
	`travauxAcceptes` enum('oui','non','selon_prix') DEFAULT 'selon_prix',
	`balconTerrasse` boolean DEFAULT false,
	`parkingGarage` boolean DEFAULT false,
	`cave` boolean DEFAULT false,
	`ascenseur` boolean DEFAULT false,
	`gardien` boolean DEFAULT false,
	`calme` boolean DEFAULT false,
	`lumineux` boolean DEFAULT false,
	`procheTransports` boolean DEFAULT false,
	`procheEcoles` boolean DEFAULT false,
	`accessibilitePmr` boolean DEFAULT false,
	`animaux` boolean DEFAULT false,
	`exposition` varchar(32),
	`autresCriteres` text,
	`budgetMax` int NOT NULL,
	`modeFinancement` enum('comptant','credit','mixte') NOT NULL,
	`apportPersonnel` int,
	`accordBancaire` enum('oui','non','en_cours') DEFAULT 'non',
	`banqueCourtier` varchar(128),
	`revenusNets` int,
	`typeMandat` enum('simple','exclusif') DEFAULT 'simple',
	`dureeMandat` int DEFAULT 3,
	`statut` enum('nouveau','en_cours','en_attente_retour','standby','traite','annule') NOT NULL DEFAULT 'nouveau',
	`notesInternes` text,
	`assigneA` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mandats_recherche_id` PRIMARY KEY(`id`)
);
