CREATE TABLE `commissions_courtage` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dossierCourtageId` int NOT NULL,
	`beneficiaireType` enum('courtier','ambassadeur') NOT NULL,
	`beneficiaireId` int NOT NULL,
	`niveau` enum('1','2') NOT NULL,
	`tauxPourcent` int NOT NULL,
	`commissionSigmaHt` int NOT NULL,
	`montantHt` int NOT NULL,
	`statut` enum('a_payer','facture_recue','paye') NOT NULL DEFAULT 'a_payer',
	`datePaiement` varchar(32),
	`reference` varchar(128),
	`valideParAdmin` boolean NOT NULL DEFAULT false,
	`valideParNom` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `commissions_courtage_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `courtiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nom` varchar(128) NOT NULL,
	`prenom` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`telephone` varchar(32) NOT NULL,
	`adresse` text NOT NULL,
	`codePostal` varchar(10) NOT NULL,
	`ville` varchar(128) NOT NULL,
	`statut` enum('auto_entrepreneur','eirl','eurl','sasu','sarl','autre') NOT NULL,
	`siret` varchar(32),
	`cabinetNom` varchar(256),
	`numeroOrias` varchar(32),
	`specialites` text,
	`parrainId` int,
	`parrainAmbassadeurId` int,
	`niveau` enum('1','2') NOT NULL DEFAULT '1',
	`conventionSignee` boolean NOT NULL DEFAULT false,
	`dateSignature` timestamp,
	`signatureNom` varchar(256),
	`conventionPdfUrl` text,
	`conventionPdfKey` varchar(512),
	`statutInterne` enum('en_attente','actif','suspendu','resilie') NOT NULL DEFAULT 'en_attente',
	`notesInternes` text,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `courtiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dossiers_courtage` (
	`id` int AUTO_INCREMENT NOT NULL,
	`courtierId` int NOT NULL,
	`clientNom` varchar(256) NOT NULL,
	`clientEmail` varchar(320),
	`clientTelephone` varchar(32),
	`typeDossier` enum('credit_immobilier','credit_professionnel','rachat_credit','credit_conso','autre') NOT NULL,
	`montantFinancement` int,
	`description` text,
	`honorairesTotal` int,
	`commissionSigmaHt` int,
	`partCourtierHt` int,
	`dateEncaissement` varchar(32),
	`statut` enum('nouveau','en_cours','en_attente_banque','accepte','refuse','finalise','annule') NOT NULL DEFAULT 'nouveau',
	`notesInternes` text,
	`assigneA` varchar(128),
	`commissionsCalculees` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dossiers_courtage_id` PRIMARY KEY(`id`)
);
