CREATE TABLE `tableaux_courtage` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`mandatId` int,
	`nom` varchar(128) NOT NULL,
	`prenoms` varchar(256) NOT NULL,
	`email` varchar(320) NOT NULL,
	`telephone` varchar(32) NOT NULL,
	`situationPro` enum('salarie_cdi','salarie_cdd','fonctionnaire','independant','chef_entreprise','retraite','sans_emploi','autre') NOT NULL,
	`employeur` varchar(128),
	`ancienneteEmploi` varchar(64),
	`salaireNet` int,
	`autresRevenus` int,
	`natureAutresRevenus` varchar(256),
	`conjointSituationPro` enum('salarie_cdi','salarie_cdd','fonctionnaire','independant','chef_entreprise','retraite','sans_emploi','autre','non_applicable') DEFAULT 'non_applicable',
	`conjointSalaireNet` int,
	`conjointAutresRevenus` int,
	`loyerActuel` int,
	`creditImmobilier` int,
	`creditAuto` int,
	`creditConso` int,
	`autresCharges` int,
	`apportPersonnel` int,
	`origineApport` enum('epargne_personnelle','donation_familiale','vente_bien','participation_entreprise','autre'),
	`epargneResiduelle` int,
	`banquePrincipale` varchar(128),
	`incidentsFinanciers` enum('oui','non') DEFAULT 'non',
	`detailsIncidents` text,
	`montantEmprunte` int,
	`dureeEmprunt` int,
	`accordBancaire_tc` enum('oui','non','en_cours') DEFAULT 'non',
	`nomBanqueAccord` varchar(128),
	`montantAccord` int,
	`commentaires` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tableaux_courtage_id` PRIMARY KEY(`id`)
);
