CREATE TABLE `off_market_biens` (
	`id` int AUTO_INCREMENT NOT NULL,
	`titre` varchar(200) NOT NULL,
	`type_bien` varchar(100),
	`region` varchar(100),
	`departement` text,
	`prix_bien` int,
	`honoraires` int,
	`travaux_estimation` int,
	`investissement_total` int,
	`nb_lots` int DEFAULT 0,
	`lots` text,
	`surface_totale` decimal(10,2),
	`rentabilite_brute` decimal(5,2),
	`rentabilite_potentielle_ld` decimal(5,2),
	`rentabilite_potentielle_cd` decimal(5,2),
	`revenus_annuels` int,
	`revenus_potentiels_ld` int,
	`revenus_potentiels_cd` int,
	`situation` text,
	`images` text,
	`image_principale` text,
	`statut` enum('disponible','sous_compromis','vendu','archive') DEFAULT 'disponible',
	`source` varchar(50) DEFAULT 'off_market',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `off_market_biens_id` PRIMARY KEY(`id`)
);
